### PR TITLE
[FIX] Import tract docs

### PR DESCRIPTION
**Pull request by 36000**
Two things here:
1. Update docs regarding name change to import_tract for importing custom tractographies
2. Only run additional bundle recognition like endpoint filtering and orientation filtering if streamlines are found in the first place

### CODE REVIEW

**Comment by 36000** [comment]
@arokem this is ready for review / merge. All of the changes in AFQ/segmentation.py are because of indent after: `if len(possible_fibers) > 0:` (so not a lot has actually changed here)

**Comment by 36000** [comment]
There is already this line: https://github.com/yeatmanlab/pyAFQ/blob/e73ea77d2a2e2c3cbedd485ccc271572e0fabced/AFQ/segmentation.py#L693

**Comment by arokem** [comment]
Oh! That works. I'll wait for the docbuild to finish and then merge this.

**Comment by arokem** [comment]
OR still seems to be pretty finicky. But I think we should solve that elsewhere, so merging.

**Pull request merged**
