### PR TITLE
Tractography

### PR DESCRIPTION
**Pull request by arokem**
First pass at tractography: this does deterministic tracking with CSD. Fitting the model and doing the tracking are separated into two different steps, and CSD parameters are stored as a nifti file.

### CODE REVIEW

**Comment by arokem** [comment]
Check it out @jyeatman : I managed to write one function that does both deterministic and probabilistic tracking from both the tensor and CSD. It will probably also accommodate other kinds of models, as we add them. So, we can use SFM (which has an ODF), and eventually also DKI (which has an ODF as well), but we can already use CSA, QBall, and other models that have SHM representations as well.

**Comment by arokem** [comment]
Ugh. We seem to be running into https://github.com/nipy/dipy/issues/852

**Comment by jyeatman** [comment]
This should work fine on python 2.7 right?

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by arokem** [comment]
Yes. It works fine on 2.7.

It seems that MNE has a fix for this, so I will try to apply that fix here,
and then we can also port it into Dipy.

**Comment by arokem** [comment]
A stitch in time, and all that.

**Comment by arokem** [comment]
OK - with a little bit more elbow-grease, I have this now passing! 

Feel free to take a look, and make comments.

**Comment by bcipolli** [comment]
@arokem What's the best way to review this for you? It's a bit much code to really read through. Any targeted places to check, or just looking to have someone else run it locally to validate?

**Comment by arokem** [comment]
The best help is to say whether the general framework makes sense: a function that takes as arguments parameters and infers the kind of model to use for the local models, and then a switch on prob/det?

In other words, focus on `tractography.py` and `test_tractography.py`

**Comment by arokem** [comment]
But also: no need for a very thorough review at this point, I think. We'll get a better sense when we start using these things. These PRs are here more for everyone's situational awareness.

**Comment by bcipolli** [comment]
@arokem makes sense to me, that part of the code looks pretty clean!

Right, I do appreciate the awareness-building, but also want to make sure you don't get backed up on PRs too much either...

**Comment by arokem** [comment]
I think I'll start merging.

**Pull request merged**
