### PR TITLE
[ENH] Bundle montage

### PR DESCRIPTION
**Pull request by 36000**
add a bundle montage for each subject

bundle_montage

### CODE REVIEW

**Comment by 36000** [comment]
bundle_montage
I think this is a good first draft that I would like to merge, but we can revisit and refine this in the future.

**Comment by 36000** [comment]
I think we need to wait to merge this until it is rebased on #997 and the common code is extracted into functions as well.

**Comment by arokem** [comment]
Could you please go ahead and rebase now that #997 is merged?

**Comment by arokem** [comment]
The new images look great! Maybe apart from SLF_L, which fades into the background, because it's dark gray. I wonder whether there is some lighting effect that could mitigate that. Also, I'd try to make these tubes a little thinner or resample the streamlines with a lot more nodes (e.g., 1,000) so that the tubes don't look so "broken up".

**Comment by 36000** [comment]
bundle_montage

**Pull request merged**
