### PR TITLE
Convert local_directories set to list

### LINKED ISSUE #413: subsequent S3BIDSStudy.download() calls result in error
```
study.download("folder-1")
```
followed by
```
study.download("folder-2")
```
errors with
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-bd2ccf68f114> in <module>
      1 study.download(
      2     "bad-download-folder-v1",
----> 3     include_derivs="qsiprep"
      4 )

~/projects/neuro/afq/pyAFQ/AFQ/data.py in download(self, directory, include_modality_agnostic, include_derivs, include_derivs_dataset_description, suffix, overwrite, pbar)
   1156         AFQ.data.S3BIDSSubject.download
   1157         """
-> 1158         self._local_directories.append(directory)
   1159         self._local_directories = set(self._local_directories)
   1160 

AttributeError: 'set' object has no attribute 'append'
```

### PR DESCRIPTION
**Pull request by richford**
Resolves #413

### CODE REVIEW

**Comment by 36000** [comment]
This is already done in #409 . I wonder why it did not show up in that issue. Maybe I should use Resolves instead of Closes. 
Nice try (:

**Comment by richford** [comment]
Oh, glad you already did it there. Although, I could say "nice try" to you since my PR is passing and yours is not. :wink:

I might suggest making the PRs more atomic so that they correspond to semantically related groups of issues.
Also, my last commit here includes a test as it's good practice to turn bugs into tests. If you decide that you want to use your PR instead of this one to resolve #413, please steal the test modification in `test_data.py` from this branch. Either works for me.

**Comment by 36000** [comment]
This LGTM. If you fix the pep8 issues, I think it's good to merge. And very nice job on the tests! I should add some to my other PR.

**Comment by richford** [comment]
Cool, thanks!

Here's a broader question about the PEP8 issues: shouldn't the pep8speaks bot conform to the linting standards that we use in the github actions. e.g. this PR passes [here](https://github.com/yeatmanlab/pyAFQ/runs/1092634244?check_suite_focus=true#step:5:1) but pep8speaks still complains. IMO, I think if edits pass `make flake8` locally and on the github action, it should also satisfy pep8speaks. On the other hand, maybe it's desirable for pep8speaks to be more stringent than the other checks. What do you think @36000 and @arokem. If we want to modify pep8speaks, I'm happy to open a new PR for it.

**Comment by 36000** [comment]
I am going to merge this and open an issue about this pep8 discussion.

**Pull request merged**
