### PR TITLE
WIP: Started to set up tests.

### PR DESCRIPTION
**Pull request by arokem**
Also, gitignore file, some further module setup stuff.

Please don't merge yet!

### CODE REVIEW

**Comment by jyeatman** [comment]
Can you add the option to do

python setup.py develop

Then I will install and take a look

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by arokem** [comment]
Let me see if I can figure out how to do that...

**Comment by arokem** [comment]
Also - @jyeatman : could you flip the switch on for Travis CI? You'd need to go here: https://travis-ci.org/, sign up with your github account, go into your profile, find the rep and flip a switch that makes it run the CI every time there's a pr.

**Comment by arokem** [comment]
`python setup.py develop` 

should work now (on this branch).

**Comment by jyeatman** [comment]
@arokem okay I'll test. What is travis ci?

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by arokem** [comment]
CI stands for "continuous integration". It's a system that installs the
software and runs our tests for us on a remote machine. For example:

https://travis-ci.org/arokem/pyAFQ/jobs/113222293

For now, it's only running things off my fork, but you'll need to flip that
switch on to get it running from the main fork.

The failure is because this also makes sure that we format our code nicely,
which we aren't yet doing apparently...

**Comment by jyeatman** [comment]
Is it safe to give these folks all the requisite permissions for the github
account?

Also, I was going to merge in all the AFQ-notebooks unless you have any
opposition

On Wednesday, March 2, 2016, Ariel Rokem <notifications@github.com> wrote:

> CI stands for "continuous integration". It's a system that installs the
> software and runs our tests for us on a remote machine. For example:
>
> https://travis-ci.org/arokem/pyAFQ/jobs/113222293
>
> For now, it's only running things off my fork, but you'll need to flip that
> switch on to get it running from the main fork.
>
> The failure is because this also makes sure that we format our code nicely,
> which we aren't yet doing apparently...
>
> On Wed, Mar 2, 2016 at 12:20 PM, Jason D. Yeatman <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > @arokem okay I'll test. What is travis ci?
> >
> > Jason D. Yeatman, PhD
> > Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
> > Department of Speech & Hearing Sciences
> > University of Washington
> > http://depts.washington.edu/bdelab/
> >
> > On Wed, Mar 2, 2016 at 12:06 PM, Ariel Rokem <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > python setup.py develop
> > >
> > > should work now (on this branch).
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/yeatmanlab/pyAFQ/pull/5#issuecomment-191404011>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/yeatmanlab/pyAFQ/pull/5#issuecomment-191410545>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yeatmanlab/pyAFQ/pull/5#issuecomment-191420751>.
>


-- 
Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by arokem** [comment]
Yes. Quite safe. It's not like we're giving them write permissions on our repo, or anything like that.

Please do add the notebooks into the doc/notebooks directory. Would be good to deprecate that other repo and start converging. If you don't mind, could you do that on a separate branch, so we don't get into conflicts?

**Comment by jyeatman** [comment]
okay. Just did that. Also merged all of your branches that didn't have
conflicts

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by arokem** [comment]
Cool. I am still sorting out this branch -- will need to be a bit more sophisticated to accomodate the gtab and affine.

**Comment by arokem** [comment]
OK - this now includes tests of the initialization of the AFQ object, on top of all the other merged code. 

Some of the code in there is still not being covered by the tests (you can read that out here: https://travis-ci.org/arokem/pyAFQ/jobs/113302061#L294. It's mostly the newer skull-stripping stuff, that's not fully worked out yet. Maybe we merge this now, and continue the work on another branch.

**Pull request merged**
