### PR TITLE
[ENH] try to get the tag name even not on release

### PR DESCRIPTION
**Pull request by 36000**

### CODE REVIEW

**Comment by arokem** [comment]
Looking [here](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) would `GITHUB_REF_NAME` work? That is described as the "The branch or tag name that triggered the workflow run". Would it include uwanted cruft?

**Comment by arokem** [comment]
Should we go ahead and merge this?

**Comment by 36000** [comment]
GITHUB_REF_NAME might work, but this is tested to work as well. I think we can merge this.

**Comment by arokem** [comment]
Should I push a new tag to try it out?

**Comment by arokem** [comment]
I will go ahead and try

**Comment by arokem** [comment]
It works! https://github.com/orgs/nrdg/packages/container/pyafq/10528786?tag=0.9.2

**Pull request merged**
