### PR TITLE
Clips streamlines by the inclusion ROI.

### PR DESCRIPTION
**Pull request by arokem**
Address #157.

This is in the right direction, but requires more validation.

### CODE REVIEW

**Comment by 36000** [comment]
- [ ] take out of examples; make unit test and test yourself

**Comment by 36000** [comment]
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ARC_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ARC_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ATR_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ATR_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_CGC_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_CGC_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_CST_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_CST_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_FA_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_FP_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_IFO_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_IFO_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ILF_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ILF_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_SLF_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_SLF_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_UNC_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_UNC_R_viz

**Comment by 36000** [comment]
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ATR_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ATR_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_CGC_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_CGC_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_CST_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_CST_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_FA_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_FP_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_IFO_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_IFO_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ILF_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ILF_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_SLF_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_SLF_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_UNC_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_UNC_R_viz

**Comment by 36000** [comment]
@arokem this should be good to go.

**Comment by arokem** [comment]
Looks good! Did you have a chance to run this with some of our data after reordering clipping/filtering?

**Comment by 36000** [comment]
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ATR_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ATR_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_CGC_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_CGC_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_CST_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_CST_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_FA_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_FP_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_IFO_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_IFO_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ILF_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_ILF_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_SLF_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_SLF_R_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_UNC_L_viz
sub-1241_ses-pre_acq-b1500_aligned_trilin_dwi_space-RASMM_model-DTI_desc-det-AFQ_UNC_R_viz

**Comment by 36000** [comment]
@arokem  posted above are the results after reordering (I deleted pre-re ordering results, it made scrolling through this PR confusing for me). Should be ready for review / merge if these tests pass

**Comment by arokem** [comment]
Looks good!

**Pull request merged**
