### PR TITLE
[FIX] pin astroid

### PR DESCRIPTION
**Pull request by 36000**

### CODE REVIEW

**Comment by 36000** [comment]
@arokem it was astroid, not sphinx! Merging and rebasing other PRs.

**Comment by arokem** [comment]
Good catch! How did you realize it was astroid? Has it been reported on the astroid bug tracker?

**Comment by 36000** [comment]
I looked more closely at the timeline and realized it was the only one that updated at the right time to cause this error (other than the AWS packages which are always updating)

**Comment by arokem** [comment]
Looks like this will be fixed in an upcoming release of sphinx-autoapi: https://github.com/readthedocs/sphinx-autoapi/issues/407, so we should keep our eyes out for that. This fix should be fine for now, though.

**Pull request merged**
