### PR TITLE
[FIX] this is a quick fix for the problem with using the default config file

### LINKED ISSUE #767: Trouble with pyAFQ CLI
This seems related to issue 763.

I have tried running pyAFQ with two different config.toml files (config_emu-AFQ.toml, config_emu-UNC.toml), where I was previously successful with config_emu-AFQ.toml. Installed (version 0.9) via pip in a new conda environment (python=3.8). I have the same error in Mac OSx, Ubuntu 20.04, and RHEL 7. Running via `$ pyAFQ config.toml --notrack |& tee log`.

I will attach the file tree, config files (txt versions for github), and captured stdout/err (log). Additionally, this is resolved via fix.py (txt here), so I'm pretty confident it is not my config.toml file, but the way an (empty) dictionary is passed between modules?

Finally, I would love an entrypoint or some guidance on the docker image, and to be able to convert the image to a singularity for CLI usage.

Big fan of your work!

Config files:
[config_emu-AFQ.txt](https://github.com/yeatmanlab/pyAFQ/files/7499476/config_emu-AFQ.txt)
[config_emu-UNC.txt](https://github.com/yeatmanlab/pyAFQ/files/7499484/config_emu-UNC.txt)

Log files:
[log_emu-AFQ.txt](https://github.com/yeatmanlab/pyAFQ/files/7499498/log_emu-AFQ.txt)
[log_emu-UNC.txt](https://github.com/yeatmanlab/pyAFQ/files/7499499/log_emu-UNC.txt)

Fix files:
[fix.txt](https://github.com/yeatmanlab/pyAFQ/files/7499503/fix.txt)
[log_fix.txt](https://github.com/yeatmanlab/pyAFQ/files/7499504/log_fix.txt)

Tree:
Screen Shot 2021-11-08 at 2 03 48 PM

### PR DESCRIPTION
**Pull request by 36000**
Fixes #767 and #763 . I think this whole system will be redesigned in #764 anyways. The problem here is that the default config file was being populated with the default params from each function's documentation, but in in the seed mask case, that default is None. We want by default to replace the `None` arguments with proper seed mask definitions in this case. If the user doesn't want to mask, they should use FullMask

### CODE REVIEW

**Comment by arokem** [comment]
Any chance we could put in place a test (nightly, possibly) that fails without this fix? Or does #764 obviate all this? Either way, we should probably put out a micro-release with this fix, even before #764 is ready to merge.

**Comment by 36000** [comment]
Yes, I can put it in an existing nightly test. Do you understand this current iteration error?

**Comment by arokem** [comment]
Not sure, but there's a new release out for pybids (released yesterday), so
that might be at the root of this.

Are you seeing this locally?

**Comment by 36000** [comment]
It pass locally, I updated pyBIDS, then it did not pass

**Comment by arokem** [comment]
OK. If this passes, we should merge this PR, make a new 0.9.1 (maybe after also merging #769?), and then proceed to debug this (possibly raising an issue in pybids, if it's on their end). I don't think that we'd like to pin pybids in the long run.

**Pull request merged**
