### PR TITLE
Update plots to paper Quality

### LINKED ISSUE #292: Plotting tract profiles should include individual tract profiles, faded, with average in bold
Like in afq browser. Could also include 1 sigma or 2 sigma lines.

### PR DESCRIPTION
**Pull request by 36000**
- [x] Make better legend
- [x] Savefig not working with seaborn
- [x] make brain_axes also iterate over bundles to create the x/y axis labels, etc
- [x] only disable unused axes
- [x] update the reliability plots to seaborn
- [x] label the plots with letters
- [x] 	Divide contrast index by 2
- [x] lateral contrast index should use contrast index
Resolves #292

### CODE REVIEW

**Comment by arokem** [comment]
You might want to coordinate with @grotheer. I think that she was working on similar things at the sprint today, with the intention of integrating in here as well.

**Comment by 36000** [comment]
image
image
image
image
image
image
image
image

**Comment by 36000** [comment]
@arokem  what do you think of the plots so far? Do you think we should merge this and add any new plots as different PRs?

**Comment by arokem** [comment]
These look great. I'll give it a review probably later tonight. And then I think we can merge it, and follow up in other PRs.

**Comment by arokem** [comment]
This looks good. We might consider simplifying the laterality index, which currently has some redundancy, but we can do that later (it’s nice to see the strong laterality in arcuate, replicating previous results!)

**Pull request merged**
