### PR TITLE
[FIX] Add exclusion ROI to IFOF

### PR DESCRIPTION
**Pull request by 36000**

### CODE REVIEW

**Comment by 36000** [comment]
@arokem this is ready for review/merge

**Comment by arokem** [comment]
Oh - interesting - the spurious streamlines follow the arcuate trajectory? 

Have you had a chance to try this out with some data? Would be good to have a few examples where we know IFOF previously captured these spurious streamlines. One example would be `sub-NDARAA948VFH_ses-HBNsiteRU` from HBN (which we use in the visualization examples). We can also use tractoscope to find some other examples in HBN.

**Comment by 36000** [comment]
I have tried this on a few subjects and it does remove the spurious streamlines. Also, both the CGC and ARC worked but ARC seemed slightly better placed.

**Comment by arokem** [comment]
OK - let me give this a try with some data as well, and then (barring any objections) we can merge it.

**Review by arokem — APPROVED** [review]
OK - I've tried this and looked closely at the ROIs, and I agree that this looks good. Merging!

**Pull request merged**
