### PR TITLE
Read and resample ROI data.

### PR DESCRIPTION
**Pull request by arokem**
This is a utility function for handling user-provided ROIs that are registered to MNI space, but are stored with an affine that differs from MNI.

### CODE REVIEW

**Comment by arokem** [comment]
TODO: 

- [ ] Test

**Comment by jyeatman** [comment]
1) I would suggest having the default be 'MNI' rather than NONE. That way it is clear reading the first line that the data is resampled to the MNI template. NONE should probably do nothing

2) Should there be a check to see if the affine matches the MNI affine? If I understand correctly, this is only necessary if they have different affines

**Comment by jyeatman** [comment]
I would suggest renaming to read_template_roi since (I think) this would just be intended for template rois not for native space rois
Or maybe read_roi_resample

**Comment by 36000** [comment]
> 1. I would suggest having the default be 'MNI' rather than NONE. That way it is clear reading the first line that the data is resampled to the MNI template. NONE should probably do nothing
> 2. Should there be a check to see if the affine matches the MNI affine? If I understand correctly, this is only necessary if they have different affines

To address #1, I think it is common in python to have default arguments be `None`, which are then replaced by the actual default. See: https://unhashable.com/always-use-none-for-default-args-in-python/ . It's also something we commonly do in pyAFQ already. The docstrings explain what None does. However, if its important to give the user the option to not resample, we could make it so passing `False` means no resampling.

**Comment by 36000** [comment]
My vote is for read_resample_roi , but read_roi is also good

**Comment by 36000** [comment]
LGTM

**Pull request merged**
