### PR TITLE
Divide nightly test into 2; have nightly tests only do nightly tests

### PR DESCRIPTION
**Pull request by 36000**
This should help with OOM error or at least binary search for the test causing it.

### CODE REVIEW

**Comment by arokem** [comment]
Could you do the same resampling for the visualization you did for the updated api example? In case the oom is because of the visualization tests

**Comment by arokem** [comment]
Could you do the same resampling for the visualization you did for the updated api example? In case the oom is because of the visualization tests

**Comment by 36000** [comment]
I checked, and I dont think any of these tests make visualizations. Only test_AFQ_data_waypoint does, which is a part of the normal tests.

**Comment by arokem** [comment]
Oh - I just realized that we'd need to merge this to master to get this to work. Merging.

**Pull request merged**
