### PR TITLE
Multi-shell, multi-tissue model

### LINKED ISSUE #367: Add support for MSMT
Need https://github.com/dipy/dipy/pull/2191 to land first

### PR DESCRIPTION
**Pull request by arokem**
Based on [this](https://dipy.org/documentation/1.2.0./examples_built/reconst_mcsd/#example-reconst-mcsd) example, adds a new model to the CSD module.  

Closes #367 and along the way also addresses #473.

### CODE REVIEW

**Comment by arokem** [comment]
OK - I think that this is ready to go. @36000 : would you mind reviewing this when you get a chance?

**Comment by arokem** [comment]
Looks like cvxpy has some issues with Python 3.8. I will investigate.

**Comment by 36000** [comment]
This looks great! Is everything squared away on Dipy's end?

**Comment by arokem** [comment]
Yes. On further inspection, I don't think that this is a Python 3.8 issue specifically. Rather, I think we might be hitting something related to this PR: https://github.com/dipy/dipy/pull/2221 (short version: cvxpy sometimes fails in hard-to-predict ways) so it's resolved on DIPY and we should get that fix here once DIPY 1.3 is released. The question is whether we should tolerate it for now and hope it doesn't bite us too often, or patch this into _fixes.

**Comment by 36000** [comment]
I think we should patch this into fixes if we want to add this to 0.5 , so 0.5 is stable.

**Comment by arokem** [comment]
OK - done in https://github.com/yeatmanlab/pyAFQ/pull/474/commits/955433bd876ae81a6fe9a2ccdfb38b59c0bfeb00.

**Comment by 36000** [comment]
This is good to merge?

**Comment by arokem** [comment]
Yes

**Pull request merged**
