### PR TITLE
Adds engine:serial default

### PR DESCRIPTION
**Pull request by teresamg**

### CODE REVIEW

**Comment by arokem** [comment]
Thanks for adding this! IIUC, this is a followup to #1124? 

Could you say a little about the errors that you are seeing without the addition of this line?

**Comment by teresamg** [comment]
GroupAFQ's parallel_params defaults to engine: serial, and this should still happen when using ParallelGroupAFQ. If there were errors with this line we can try something else?

**Comment by arokem** [comment]
Yeah, I think for now users would have to add: `"engine" : "serial"` to their code, along the lines of: 

```
import os.path as op

from AFQ.api.group import ParallelGroupAFQ
from AFQ.definitions.image import RoiImage
import AFQ.api.bundle_dict as abd
import AFQ.data.fetch as afd


_, bids_path = afd.fetch_hbn_preproc(
        ["NDARZT957CWG",
         "NDARZU279XR3",
         "NDARZU401RCU",
         "NDARZU822WN3",
         "NDARZV421TCZ",
         "NDARZW262ZLV",
         "NDARZX163EWC",
         ],
        path="/gscratch/scrubbed/arokem/data/")
    
my_afq = ParallelGroupAFQ(
    bids_path=bids_path,
    preproc_pipeline="qsiprep",
    parallel_params={
        "engine" : "serial",
        "submitter_params": {
            "plugin": "slurm",
            "sbatch_args": "-J test \
                            -p ckpt \
                            --nodes=1 \
                            --cpus-per-task=8 \
                            --gpus=1 \
                            -A escience \
                            --mem=64G \
                            --time=2:00:00 \
                            -o /gscratch/scrubbed/arokem/logs/test.out \
                            -e /gscratch/scrubbed/arokem/logs/test.err \
                            --mail-user=arokem@uw.edu \
                            --mail-type=ALL"
        },
        "cache_dir": "/gscratch/scrubbed/arokem/tmp"
    }
)

my_afq.export_all()
```

Is that correct?

**Comment by teresamg** [comment]
It should run, but users won't always know to specify engine: serial, and don't have to unless specifying other parameters, so I think the default should be in there somehow!

**Comment by 36000** [comment]
This makes sense to me! Merging

**Pull request merged**
