### PR TITLE
Use a simpler way of using tqdm on the tractography

### PR DESCRIPTION
**Pull request by 36000**
Now we aren't maintaining our own tracking class. Also removes min length, but this can now be handled in the bundle definitions.

### CODE REVIEW

**Comment by arokem** [comment]
What's the motivation to ditch `min_length`?

**Comment by 36000** [comment]
We now have this in the bundle recognition step

**Comment by 36000** [comment]
Do you think I should make a PR on dipy to add min_length to the tractography up there? Like do you think it is a feature that other DIPY users will find useful?

**Comment by arokem** [comment]
I think so! It's nice to do this while tracks are being generated (i.e., by not `yield`ing them), so you don't have to store these very short streamlines in memory at any point.

**Pull request closed without merging**
