### PR TITLE
WIP: Add OR fetcher and example

### PR DESCRIPTION
**Pull request by arokem**
- [ ]  Update example to use the API with OR-oriented config.

### CODE REVIEW

**Comment by 36000** [comment]
Do you think this is caused by running out of RAM? We might need to break the docs up into separate github actions.

**Comment by arokem** [comment]
I think that the failure might be related to https://github.com/dipy/dipy/pull/2210. PFT just occasionally segfaults without any obvious reason. I think that I will switch over to another tractography method here.

**Comment by 36000** [comment]
I just checked code, LGTM

**Comment by arokem** [comment]
Can confirm that this works locally on my laptop as well

**Pull request merged**
