### PR TITLE
Segmentation

### PR DESCRIPTION
**Pull request by arokem**
This needs to follow #20 and #21

### CODE REVIEW

**Comment by jyeatman** [comment]
The logic here makes sense to me

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by arokem** [comment]
First pass of segmentation of CST in that notebook: 
output_kmhlqf

What do you think, @jyeatman? Lot's of outliers, huh?

**Comment by jyeatman** [comment]
I think that it is awesome that you got a video inserted in this message.
No idea how you did it.

There are a number of reasons for these outliers that we can take care of
in future iterations with cleaning etc. But given the noise, this will also
be a good test of the fascicle registration once we segment for a few
subjects

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by arokem** [comment]
OK. For the time being, I am going to push forward to integrate everything that is in that notebook into module code, and figure out a way for us to test this stuff.

**Comment by jyeatman** [comment]
sounds good

then we can run on a bunch of hcp subject and test registration etc

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by arokem** [comment]
And now a few more groups as well. This is a whole brain tractography, down-sampled by a factor of 50 (that is, only 1 out of 50 streamlines is considered). 

output_osvgxe

**Comment by arokem** [comment]
What's the deal with the "FA" and "FP" ROIs? They don't have a "roi1" and "roi2" like all the others. How do we use them for the segmentation?

**Comment by jyeatman** [comment]
Those are forceps major and forceps minor. In other words genuine and
selenium. Probably better to skip those and use the specific CC Roos we have

On Thursday, May 26, 2016, Ariel Rokem <notifications@github.com> wrote:

> What's the deal with the "FA" and "FP" ROIs? They don't have a "roi1" and
> "roi2" like all the others. How do we use them for the segmentation?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/yeatmanlab/pyAFQ/pull/22#issuecomment-222023116>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABsYygsUma7yPIAiiXayx82FlRO6GdN3ks5qFixngaJpZM4IZyu6>
> .
>


-- 
Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by arokem** [comment]
Gotcha. For the callosal ROIs: the rules there are that the streamline has
to pass through the corpus callosum and through the two twin ROIs on each
side?

So, for example `"callosum", "L_occipital", "R_occipital"]` are the
inclusion ROIs for one group, and `["callosum", "L_PostParietal",
"R_PostParietal"]` are the inclusion ROIs for another group, etc. ?

**Comment by arokem** [comment]
BTW, here is a segmentation of a full connectome tracked from DTI (deterministic; ~100k streamlines)
output_hrsa7r

**Comment by jyeatman** [comment]
Yeah that's right. There has been some debate about whether the other rois
should be exclusion, but for now let's keep simple

On Thursday, May 26, 2016, Ariel Rokem <notifications@github.com> wrote:

> Gotcha. For the callosal ROIs: the rules there are that the streamline has
> to pass through the corpus callosum and through the two twin ROIs on each
> side?
>
> So, for example `"callosum", "L_occipital", "R_occipital"]` are the
> inclusion ROIs for one group, and `["callosum", "L_PostParietal",
> "R_PostParietal"]` are the inclusion ROIs for another group, etc. ?
>
> On Thu, May 26, 2016 at 5:24 PM, Jason D. Yeatman <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Those are forceps major and forceps minor. In other words genuine and
> > selenium. Probably better to skip those and use the specific CC Roos we
> > have
> >
> > On Thursday, May 26, 2016, Ariel Rokem <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > What's the deal with the "FA" and "FP" ROIs? They don't have a "roi1"
> and
> > > "roi2" like all the others. How do we use them for the segmentation?
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/yeatmanlab/pyAFQ/pull/22#issuecomment-222023116>,
> > or mute
> > > the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/ABsYygsUma7yPIAiiXayx82FlRO6GdN3ks5qFixngaJpZM4IZyu6
> > >
> > > .
> > >
> >
> >
> > --
> > Jason D. Yeatman, PhD
> > Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
> > Department of Speech & Hearing Sciences
> > University of Washington
> > http://depts.washington.edu/bdelab/
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/yeatmanlab/pyAFQ/pull/22#issuecomment-222030673>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AAHPNkcXwkqUev2HC78wysSVYDj1ZDj-ks5qFjmrgaJpZM4IZyu6
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/yeatmanlab/pyAFQ/pull/22#issuecomment-222033277>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABsYyjBCIM4WZUQvxFB1SxcuwyMT-z1xks5qFj6EgaJpZM4IZyu6>
> .
>


-- 
Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by arokem** [comment]
OK. This one is probably ready to go. It's pretty humongous, and I don't expect anyone to actually read it in detail. There's probably also more work that needs to be done in many corners of this (in particular, parallelization of tracking is still not working as expected -- not wrong, just not as fast as I would have hoped). But, unless there is any objections, let's merge this one, and keep going from here.

**Comment by bcipolli** [comment]
👍

**Pull request merged**
