### PR TITLE
Starting to adapt to DIPY 1.0 API.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by arokem** [comment]
This now passes locally on my machine (against current DIPY master branch), so it should pass on the CI, as soon as DIPY 1.0 is released.

**Comment by 36000** [comment]
The examples need to be adapted as well. For example, move_streamlines in plot_tract_profile should be transform_tracking_output I think.

**Comment by arokem** [comment]
Maybe we can take that on a separate branch, once everything is passing here?

**Comment by arokem** [comment]
OK - this passes the tests now, with dipy 1.0 released.

@36000 : would it be OK to merge this into master now? I believe that you could then keep going on your work in #136. 

And we can come back to fix the examples for the new API.

**Comment by 36000** [comment]
It is OK to merge!

**Pull request merged**
