### PR TITLE
Use argparse instead of optparse

### PR DESCRIPTION
**Pull request by richford**
Resolves issue #44. See discussion in #44 for more details.

### CODE REVIEW

**Comment by arokem** [comment]
@jyeatman : how do you feel about this API? Users would have to type `pyAFQ_fit dti file.nii.gz file.bval file.bvec` or something like that. 

I think that the previous API is marginally clearer, because the different options are available to users through the tab-completion (i.e. which models they could fit). 

We could reduce code duplication by putting all the duplicate code in a `cli.py` module in the package portion of the library.

**Comment by richford** [comment]
Good point about the tab completion. FYI, use pyAFQ_fit -h or pyAFQ_fit --help to see the new API.

**Comment by jyeatman** [comment]
I'm fine either way. I don't think it will be difficult to update the
matlab code. I think we should go with whatever you think will be the best
for our long term vision of having many models etc

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by arokem** [comment]
Let's go with this change then.

TBH, it's not that crucial: the CLIs are mostly meant for Matlab users ;-)

And I think that this change will make things slightly easier to extend
with more models.

**Comment by arokem** [comment]
I think this is now subsumed in #94 that was just merged. I'll close this one.

**Pull request closed without merging**
