### PR TITLE
[FIX] use plotly cmap instead of matplotlib cmap in plotly_backend

### PR DESCRIPTION
**Pull request by 36000**

### CODE REVIEW

**Comment by 36000** [comment]
I think this new colorscale also looks a little better
image

**Comment by arokem** [comment]
I think this kind of data is best visualized with a sequential (not
diverging) colormap. I think that "viridis" would work well here.

**Comment by 36000** [comment]
I was basing it off of the mAFQ implementation
image

**Comment by arokem** [comment]
No one should ever use that colormap (jet) for anything: https://jakevdp.github.io/blog/2014/10/16/how-bad-is-your-colormap/

**Comment by 36000** [comment]
Here is viridis:
image
This plot from the "jet" rant in particular is very interesting:
image

**Comment by 36000** [comment]
newplot
Here are all of plotly's built in sequential colors, as well

**Comment by arokem** [comment]
I think viridis looks great for this!

**Pull request merged**
