### PR TITLE
[ENH] Update the docker worklow to hopefully push tags, as well as remove AFQsi docker

### PR DESCRIPTION
**Pull request by 36000**

### CODE REVIEW

**Comment by 36000** [comment]
@arokem is this what you had in mind for a new yaml? I also deleted afqsi docker as I don't think it will be needed soon.

**Comment by arokem** [comment]
Yes. I think so. Let's see how this works with 0.9.1 🤞

**Comment by arokem** [comment]
And +1 to removing afqsi, which should soon be superseded by the qsiprep docker image.

**Comment by arokem** [comment]
Whoops. I think that I merged this prematurely. Is it possible that you didn't add the 'docker-push.sh' script? No hurry, of course - I am only looking at this now because my kiddos just went to sleep.

**Pull request merged**
