### PR TITLE
Update example to serve as a CI target

### PR DESCRIPTION
**Pull request by arokem**
The column names were updated in #279, and this follows that update.

The note that used to be here is no longer correct 🎉 

Also, we might want to always run this in the CI. Let's see how long this takes.

### CODE REVIEW

**Comment by arokem** [comment]
With this implemented, documentation builds take about 50 minutes. But, this has the advantage of satisfying some of the requirements of #372. I would like to also add generation of the GIFs and embedding these into the examples page. That would be a think to quickly check when we are making changes to default processing or API.

**Comment by 36000** [comment]
A few ideas:
- [ ] Not running the other tests would save 10 minutes.
- [ ] We could only generate gifs for a few key tracts.
- [ ] We could also reduce the number of tracts we end up plotting by setting n_seeds to a very small number ~(1-10k) and random_seeds to true in tractography.

**Comment by arokem** [comment]
[ ] Experiment with embedding plotly htmls into the example webpage.

**Comment by arokem** [comment]
Not sure I understand this suggestion: 

> Not running the other tests would save 10 minutes.

The tests are not running in the documentation build CI workflow. Or do you mean running the other examples?

**Comment by 36000** [comment]
I meant not running the other examples. But that is more of a last resort.

**Comment by arokem** [comment]
Need to understand how the viewers are embedded in this example: https://brainsprite.github.io/auto_examples/plot_anat.html#sphx-glr-auto-examples-plot-anat-py

**Comment by arokem** [comment]
Or maybe better: https://github.com/plotly/plotly-sphinx-gallery/blob/master/examples/plot_plotly.py

**Comment by arokem** [comment]
This is very neat: the resulting example now includes an interactive visualization of all the segmented bundles. 

To avoid running this every time, we could use something like: https://github.com/Khan/pull-request-comment-trigger.

**Comment by arokem** [comment]
@deploy

**Comment by arokem** [comment]
build

**Comment by arokem** [comment]
build

**Comment by arokem** [comment]
I gave up on triggering the builds with comments. I think that this is ready to merge, but happy for more feedback.

**Comment by 36000** [comment]
I fixed the bug this is catching in #395 which was introduced in #393 . May want to wait and rebase this on that, to make sure you are passing.

**Comment by 36000** [comment]
Otherwise, LGTM!

**Comment by arokem** [comment]
OK. I think that this is done for now. I will merge when it goes green (in about 40 minutes :-D)

**Pull request merged**
