### PR TITLE
Update to generate by for BIDS

### PR DESCRIPTION
**Pull request by 36000**
this PR is held up until pybids fixes this: https://github.com/bids-standard/pybids/issues/864
Also do not merge this until it is rebased on top of #869

### CODE REVIEW

**Comment by 36000** [comment]
Not sure why but this still doesn't work....

**Comment by 36000** [comment]
@arokem could you create a minimal example to demonstrate whether this is a pybids problem?

**Comment by arokem** [comment]
I created a gist that replicates the problem that we are seeing: https://gist.github.com/arokem/7505a75031924960fc9c18a88589900e

Along the way, I also found out that the datasets that we create in these tests do not pass BIDS validation, so I had to tweak the test data a little bit to add synthetic "raw" data (this is because you can't have a valid BIDS dataset that doesn't have subject folders at top level). 

Nevertheless, these datasets are now BIDS valid, but still when there is only a GeneratedBy field in the `dataset_description.json`, the call to `get` with the derivative scope returns an empty list, instead of the list populated with the file pointers to the files that live under that scope. I'll post an issue to the pybids GitHub as well.

**Comment by arokem** [comment]
OK - I can confirm that this will be fixed upstream when https://github.com/bids-standard/pybids/issues/864 is merged. So I guess we keep this PR open until that appears in a pybids release version.

**Pull request closed without merging**
