### PR TITLE
[ENH] Much faster mahal cleaning

### PR DESCRIPTION
**Pull request by 36000**
It my case, it reduced the clean time from around 15 minutes to around 4 seconds (225x speedup).
We do this by using numpy functions instead of for loops. In _fixes for now, but can be moved to dipy later.

### CODE REVIEW

**Comment by arokem** [comment]
This is awesome! Probably also more memory efficient (?). Can you write a test that compares it against the slow implementation? We should definitely push this upstream to DIPY.

**Comment by 36000** [comment]
Good call. I was incorrectly oversimplifying the covariance calculation, but now I fixed that. It is now around 8 seconds on my test datasets, so still a significant improvement on the dipy code, and with the same result! It is probably more memory efficient, or at least as memory efificent.

**Comment by 36000** [comment]
TODO: rename and conform to dipy api and system

**Review by arokem — APPROVED** [review]
Looks great now!

**Pull request merged**
