### PR TITLE
Adds total number of streamlines, to complete the sl counts table.

### LINKED ISSUE #464: New output: number of streamlines in each bundle
Generate a csv file that has two columns: bundle name and number of streamlines.

### PR DESCRIPTION
**Pull request by arokem**
Closes #464.

### CODE REVIEW

**Comment by arokem** [comment]
I've overhauled this a bit, so it's a separate function. Instead of two separate files, it now saves a single table with two columns: one for the bundles and the other for the cleaned bundles, also giving a sense of how many sl are removed in cleaning.

**Comment by 36000** [comment]
consider Integrating changes in #471 and make sure it passes test_AFQ_reco.

**Comment by arokem** [comment]
Ah yes: that makes sense. I was testing this only with `seg_algo='afq'`

**Comment by arokem** [comment]
OK - I will finish this before proceeding to rebase/fix #470.

**Comment by arokem** [comment]
Looks like it's working. Merging.

**Pull request merged**
