### PR TITLE
NF: Adds the free-water DTI model.

### PR DESCRIPTION
**Pull request by arokem**
Both as an ODF model, as well as scalar model.

### CODE REVIEW

**Comment by arokem** [comment]
Closes #671

**Comment by dweiss044** [comment]
An error is thrown when finding the direction using the FWDTI odf model:

INFO:AFQ.tractography:Getting Directions...
Traceback (most recent call last):
  File "/data/rauschecker1/utils/tools/pyAFQ/bin/pyAFQ", line 101, in <module>
    afb.parse_config_run_afq(
  File "/data/rauschecker1/utils/tools/pyAFQ/AFQ/utils/bin.py", line 265, in parse_config_run_afq
    getattr(myafq, to_call)()
  File "/data/rauschecker1/utils/tools/pyAFQ/AFQ/api.py", line 2291, in export_all
    self.export_bundles()
  File "/data/rauschecker1/utils/tools/pyAFQ/AFQ/api.py", line 2205, in export_bundles
    self.data_frame.apply(self._export_bundles, axis=1)
  File "/data/rauschecker1/utils/envs/pyAFQ/lib/python3.9/site-packages/pandas/core/frame.py", line 7768, in apply
    return op.get_result()
  File "/data/rauschecker1/utils/envs/pyAFQ/lib/python3.9/site-packages/pandas/core/apply.py", line 185, in get_result
    return self.apply_standard()
  File "/data/rauschecker1/utils/envs/pyAFQ/lib/python3.9/site-packages/pandas/core/apply.py", line 276, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/data/rauschecker1/utils/envs/pyAFQ/lib/python3.9/site-packages/pandas/core/apply.py", line 290, in apply_series_generator
    results[i] = self.f(v)
  File "/data/rauschecker1/utils/tools/pyAFQ/AFQ/api.py", line 1521, in _export_bundles
    bundles_file = func(row)
  File "/data/rauschecker1/utils/tools/pyAFQ/AFQ/api.py", line 1337, in _clean_bundles
    bundles_file = self._segment(row)
  File "/data/rauschecker1/utils/tools/pyAFQ/AFQ/api.py", line 1284, in _segment
    streamlines_file = self._streamlines(row)
  File "/data/rauschecker1/utils/tools/pyAFQ/AFQ/api.py", line 1241, in _streamlines
    sft = aft.track(params_file, **tracking_params)
  File "/data/rauschecker1/utils/tools/pyAFQ/AFQ/tractography.py", line 148, in track
    dg = dg.from_shcoeff(model_params, max_angle=max_angle, sphere=sphere)
  File "dipy/direction/closest_peak_direction_getter.pyx", line 206, in dipy.direction.closest_peak_direction_getter.PmfGenDirectionGetter.from_shcoeff
  File "dipy/direction/pmf.pyx", line 67, in dipy.direction.pmf.SHCoeffPmfGen.__init__
  File "/data/rauschecker1/utils/envs/pyAFQ/lib/python3.9/site-packages/dipy/reconst/shm.py", line 455, in real_sh_descoteaux
    m, n = sph_harm_ind_list(sh_order, full_basis)
  File "/data/rauschecker1/utils/envs/pyAFQ/lib/python3.9/site-packages/dipy/reconst/shm.py", line 597, in sph_harm_ind_list
    raise ValueError('sh_order must be an even integer >= 0')
ValueError: sh_order must be an even integer >= 0


This can be fixed by changing line 142 in tractography.py to:

if odf_model == "DTI" or odf_model == "DKI" or odf_model == "FWDTI":

**Comment by dweiss044** [comment]
There is no member function for AFQ._fwdti_fit(). I was able to get the pipeline to finish by adding this function to the AFQ object:

import dipy.reconst.fwdti as dpy_fwdti
  def _fwdti_fit(self, row):
      fwdti_params_file = self._fwdti(row)
      fwdti_params = nib.load(fwdti_params_file).get_fdata()
      fwmodel = dpy_fwdti.FreeWaterTensorModel(row['gtab'])
      fwfit = dpy_fwdti.FreeWaterTensorFit(fwmodel, fwdti_params)
      return fwfit

**Comment by arokem** [comment]
Thanks for taking a look! I incorporated your suggestions in eef44a3

**Comment by 36000** [comment]
Maybe we should rebase this on #675 when its done, to see how well the new interface works with new models.

**Comment by arokem** [comment]
This was superseded by #931

**Pull request closed without merging**
