### PR TITLE
FIX: Remove xvfb from being needed in tests

### PR DESCRIPTION
**Pull request by 36000**
@arokem I think this may help with the memory issues the nightly tests can run into.

- [x] add fury test

### CODE REVIEW

**Comment by arokem** [comment]
Do we want to add a workflow that tests with fury as the backend and uses XVFB? Or is that already here somewhere?

**Comment by 36000** [comment]
I think we should, that does not exist.

**Comment by arokem** [comment]
Do you want to add that here, or on a separate PR?

**Comment by 36000** [comment]
I can do that here. It will not take long to make this test 👍

**Pull request merged**
