### PR TITLE
Set logger levels to INFO

### PR DESCRIPTION
**Pull request by arokem**
Particularly for saving of files, so that we get more information about what is being saved and when. Output is more verbose, but that should help with #857, where not a lot of information is provided except for the prog bars.

### CODE REVIEW

**Comment by 36000** [comment]
Should we do this in all files? Is there some way to set this universally or have the user do it?

**Comment by 36000** [comment]
@arokem  maybe we should replace things like
```
logger = logging.getLogger('AFQ.Segmentation')
logger.info()
````
with:
```
logging.info()
```
This is what dipy uses in most cases, however in some cases they do use getlogger (like stateful tractogram) . For the size of our package I think we may not need to have our own getLogger. What do you think?

**Comment by arokem** [comment]
I don't have much experience with this. I think that using the `logging.info` function directly would be fine, so long as we can set the logging levels somewhere global. For example, in the package `__init__.py` file. And it should be possible to over-ride for users who want less verbose output everywhere.

**Comment by 36000** [comment]
Trying middle ground, setting everything to 'AFQ' logger. Does this work in the situations where we were having problems?

**Comment by 36000** [comment]
@arokem  if this also solves the problems you were seeing earlier, we can merge this

**Comment by arokem** [comment]
OK. Let's merge this and adjust if we see this is too verbose or not verbose enough.

**Pull request merged**
